### ISSUE TITLE
Redirect loop occurs if incorrect password is entered unless rememberUserCookieLifetime = 0

### ISSUE THREAD

**Issue by eqjcunningham** [patschi/adfs-themes#1]

**Comment by eqjcunningham** [comment]
https://github.com/patschi/adfs-themes/blob/7adb8d7d399b60aa4de37bb3f017a5dbcf82f3d2/remember-user-and-auto-domain/onload.add.js#L89 

This line seems to be the culprit. Works fine after commenting it out.

**Comment by patschi** [comment]
That's odd, as I've been testing this quite extensively. Are you using the paged ADFS2019 theme with the script? Any specific browser you're using?

The function `paginationManager.validateAndNext();` switches from username field to password field when called the first time. When it is run the second time, it will submit the form. (That part of code logic comes from the out-of-the-box JavaScript from Microsoft)

```javascript
        if (_self.options.currentPageIndex + 1 >= _self.options.pages.length) {
            // POST back to ADFS since there are no more pages to go to 
            document.forms['loginFormPaginated'].submit();
            return true;
        } else {
            _self.displayNextPage();
        }
```

The only situation I can imagine the redirect loop to occur is when the username field is skipped from outside my functions. Can you check the source code of your page - did you copy-paste the same code (in different forms?) twice?

**Comment by eqjcunningham** [comment]
This was tested using the paginated ADFS2019 theme with Windows Server 2022 in both Chrome and Edge. The source code was appended exactly as is to the end of the the onload.js with the only modification being the default domain. No other additions to the onload.js were made.

**Comment by patschi** [comment]
Should be fixed with https://github.com/patschi/adfs-themes/commit/f2df7b910dbba1e4b5133abb8614e801567a71f7. I use MFA with adfsmfa, and it didn't occur in that scenario during testing. Without having this set, it was indeed reproducible. Thanks for the report!
